# Generated by Django 5.2.7 on 2025-10-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('is_done', models.BooleanField()),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
